site_name: GROBID Documentation
repo_url: https://github.com/kermitt2/grobid/
repo_name: GitHub

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

site_description: Documentation for GROBID
docs_dir: doc
extra_css:
  - css/custom.css

extra_javascript:
    - doc/readthedocs-search.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
    - search
nav:
  - Home: 'index.md'
  - About:
    - 'Introduction': 'Introduction.md'
    - 'How GROBID works': 'Principles.md'
    - 'References': 'References.md'
    - 'Licence': 'License.md'
  - User manual:
    - 'Getting started': 'getting_started.md'
    - 'GROBID service': 'Grobid-service.md'
    - 'Build GROBID from source': 'Install-Grobid.md'
    - 'GROBID with containers': 'Grobid-docker.md'
    - 'GROBID configuration': 'Configuration.md'
    - 'GROBID specialized processes': 'Grobid-specialized-processes.md'
    - 'TEI encoding of results': 'TEI-encoding-of-results.md'
    - 'Coordinates of structures in the PDF': 'Coordinates-in-PDF.md'
    - 'Adding a consolidation service': 'Consolidation.md'
    - 'Training the GROBID models': 'Training-the-models-of-Grobid.md'
    - 'End-to-end evaluation': 'End-to-end-evaluation.md'
    - 'Troubleshooting and FAQ': 'Frequently-asked-questions.md'
    - 'Grobid in batch mode': 'Grobid-batch.md'
    - 'Use Grobid library in third party Java applications': 'Grobid-java-library.md'
  - Benchmarking:
    - 'Description': 'benchmarks/Benchmarking.md'
    - 'PubMed Central': 'benchmarks/Benchmarking-pmc.md'
    - 'bioRxiv': 'benchmarks/Benchmarking-biorxiv.md'
    - 'PLOS': 'benchmarks/Benchmarking-plos.md'
    - 'eLife': 'benchmarks/Benchmarking-elife.md'
  - Annotation guidelines:
    - 'General principles': 'training/General-principles.md'
    - 'Segmentation model': 'training/segmentation.md'
    - 'Fulltext model': 'training/fulltext.md'
    - 'Header model': 'training/header.md'
    - 'Bibliographical references': 'training/Bibliographical-references.md'
    - 'Affiliation-address model': 'training/affiliation-address.md'
    - 'Date model': 'training/date.md'
    - 'Monograph model': 'training/monograph.md'
  - Developer notes:
    - 'Notes for the Grobid Developers': 'Notes-grobid-developers.md'
    - 'Deep Learning models': 'Deep-Learning-models.md'
    - 'Recompiling CRF libraries': 'Recompiling-and-integrating-CRF-libraries.md'
