site_name: GROBID Documentation
repo_url: https://github.com/kermitt2/grobid/
repo_name: GitHub
theme: readthedocs
site_description: Documentation for GROBID
docs_dir: doc
plugins:
    - search
theme:
    name: readthedocs
pages:
  - Home: 'index.md'
  - About:
    - 'Introduction': 'Introduction.md'
    - 'References': 'References.md'
    - 'Licence': 'License.md'
  - User manual:
    - 'Install GROBID': 'Install-Grobid.md'
    - 'GROBID service': 'Grobid-service.md'
    - 'GROBID batch mode': 'Grobid-batch.md'
    - 'GROBID with containers': 'Grobid-docker.md'
    - 'Troubleshooting and known issues': 'Troubleshooting.md'
    - 'Java library': 'Grobid-java-library.md'
    - 'TEI encoding of results': 'TEI-encoding-of-results.md'
    - 'Coordinates of structures in the PDF': 'Coordinates-in-PDF.md'
    - 'Adding a consolidation service': 'Consolidation.md'
    - 'Training the GROBID models': 'Training-the-models-of-Grobid.md'
    - 'End-to-end evaluation': 'End-to-end-evaluation.md'
    - 'Benchmarking': 'Benchmarking.md'
  - Annotation guidelines:
    - 'General principles': 'training/General-principles.md'
    - 'Segmentation model': 'training/segmentation.md'
    - 'Fulltext model': 'training/fulltext.md'
    - 'Bibliographical references': 'training/Bibliographical-references.md'
    - 'Affiliation-address model': 'training/affiliation-address.md'
    - 'Date model': 'training/date.md'
  - Developer notes:
    - 'Developer Guide': 'Developer-guide.md'
    - 'Deep Learning models': 'Deep-Learning-models.md'
    - 'Recompiling CRF libraries': 'Recompiling-and-integrating-CRF-libraries.md'
