name: Build unstable

on: [ push ]

concurrency:
  group: gradle
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17.0.10+7'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew clean assemble --info --stacktrace --no-daemon

      - name: Test with Gradle Jacoco and Coveralls
        run: ./gradlew test jacocoTestReport coveralls --no-daemon

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          format: jacoco
          file: build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml
          debug: true
  
  docker-build-crf:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Create more disk space
        run: sudo rm -rf /usr/share/dotnet && sudo rm -rf /opt/ghc && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v2
      - name: Build and push
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_LFOPPIANO }}
          password: ${{ secrets.DOCKERHUB_TOKEN_LFOPPIANO }}
          image: lfoppiano/grobid
          registry: docker.io
          pushImage: ${{ github.event_name != 'pull_request' }}
          tags: latest-develop, latest-crf
          dockerfile: Dockerfile.crf
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  # docker-build-full:
  #   needs: [ build ]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Create more disk space
  #       run: sudo rm -rf /usr/share/dotnet && sudo rm -rf /opt/ghc && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
  #     - uses: actions/checkout@v2
  #     - name: Build and push
  #       id: docker_build
  #       uses: mr-smithers-excellent/docker-build-push@v5
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME_LFOPPIANO }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN_LFOPPIANO }}
  #         image: lfoppiano/grobid
  #         registry: docker.io
  #         pushImage: ${{ github.event_name != 'pull_request' }}
  #         tags: latest-develop
  #         dockerfile: Dockerfile.delft
  #     - name: Image digest
  #       run: echo ${{ steps.docker_build.outputs.digest }}
